Feature/localization
dynasticdevelop/place pull request #192
Opened 2017-07-26 04:19 UTC by EricRabil

Here's the localization! I did my best to get all strings from the templates.

2017-07-26 04:22 UTC, AppleBetas commented
What does this do for text generated by client-side JS?

2017-07-26 04:24 UTC, EricRabil commented
That's not taken into account in this, I can do that though. This PR only adds localization for EJS files.

2017-07-26 04:27 UTC, AppleBetas commented
Alright, we should handle that before merging this.

2017-07-27 17:14 UTC, nullpixel requested changes
minor things. when merging this, please squash

2017-07-27 17:14 UTC, nullpixel commented on .gitignore
> +yarn.lock
yarn.lock should be committed

2017-07-27 17:14 UTC, nullpixel commented on controllers/GuidelineController.js
> +    const guidelinesLocalePath = path.join(process.cwd(), "config", `community_guidelines_${res.locale}.md`);
Can we move community guidelines out of the config folder if we're going to follow this pattern

2017-07-27 17:14 UTC, nullpixel commented on locales/en.json
> +	"language_name": "English",
missing `translation_list_suffix`

2017-07-27 17:14 UTC, nullpixel commented on yarn.lock
> -# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
yarn lockfiles should be committed https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

2017-07-27 17:17 UTC, AppleBetas commented on locales/en.json
> +	"language_name": "English",
My thought was that we only use it for crediting translators and otherwise the code should just display `language_name`

2017-07-27 17:18 UTC, nullpixel commented on locales/en.json
> +	"language_name": "English",
Well, someone technically translated this

2017-07-27 17:20 UTC, AppleBetas commented on locales/en.json
> +	"language_name": "English",
Us? lol

2017-07-27 17:21 UTC, nullpixel commented on locales/en.json
> +	"language_name": "English",
yeah?

2017-07-27 17:22 UTC, AppleBetas commented on locales/en.json
> +	"language_name": "English",
I mean we coded the rest of the site but I just thought it was more fitting so we could credit translators for their work (given that they're not part of Dynastic)

2017-07-27 17:23 UTC, nullpixel commented on locales/en.json
> +	"language_name": "English",
Totally agree

2017-08-12 22:14 UTC, EricRabil commented
This is ded

2017-09-03 10:39 UTC, nullpixel commented
on hold for backend rewrite

2017-09-03 10:39 UTC, closed without merging